# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: ripple
    binary: ripple
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: ripple
    ids: [ripple]
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

nfpms:
  - id: packages
    package_name: ripple
    vendor: stone
    homepage: https://github.com/stone/ripple
    maintainer: Fredrik Steen <fredrik@tty.se>
    description: |
      DNS propagation checker

      Walks the DNS tree from root servers, finds all authoritative
      nameservers for a domain, then polls them (and a set of public
      resolvers) until the record shows up or a timeout is hit.

    license: GPL-3.0
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin

    contents:
      - src: tools/packaging/config.yaml
        dst: /etc/ripple/config.yaml
        type: config|noreplace
        file_info:
          mode: 0644
      - src: tools/packaging/ripple.service
        dst: /usr/lib/systemd/system/ripple.service
        type: config|noreplace
        file_info:
          mode: 0644
      - src: README.md
        dst: /usr/share/doc/ripple/README.md
        file_info:
          mode: 0644
      - src: LICENSE
        dst: /usr/share/doc/ripple/LICENSE
        file_info:
          mode: 0644
    scripts:
      postinstall: tools/packaging/postinstall.sh
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
    rpm:
      group: System Environment/Daemons

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: stone
    name: ripple
  draft: false
  prerelease: auto
  name_template: "{{.Version}}"
